# Generated by Django 4.0.5 on 2022-06-06 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetShop', '0002_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo_consulta', models.IntegerField()),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
